name: Dependency Review Workflow

on:
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  dependency-review:
    name: Scan dependencies for existing vulnerabilities
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
