name: Main Workflow

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        python: [ '3.10', '3.11' ]
        os: [ 'ubuntu-latest', 'windows-latest' ]
    name: Build python ${{ matrix.python }} environment on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        architecture: x64

    - name: Update pip
      run: python -m pip install -U pip

    - name: Install pipx
      run: python -m pip install pipx

    - name: Update other tools
      run: python install.py
